### ISSUE TITLE
Error trying to use the action on my project

### ISSUE THREAD

**Issue by danazkari** [Azure/setup-kubectl#1]
I tried using `azure/setup-kubectl` action, providing the documented inputs, and I'm getting the next error:

![image](https://user-images.githubusercontent.com/349542/69293299-157e7900-0bce-11ea-8d89-caef8bbeeaac.png)

I would provide more logs if I could, but that's as much as I get from GH Actions

This is the code I used to try to use the action:
```yaml
name: Publish a new production release

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/setup-kubectl@v1
      with:
        version: '1.15.0'
      id: install
      name: install kubectl client
    - name: create kubernetes config
      run: |
        cat << EOF > kube-config
        apiVersion: v1
        clusters:
        - cluster:
            certificate-authority-data: ${{ secrets.CLUSTER_CERT_AUTH_DATA }}
            server: ${{ secrets.CLUSTER_IP }}
          name: kubernetes
        contexts:
        - context:
            cluster: kubernetes
            user: kubernetes-admin
          name: kubernetes-admin@kubernetes
        current-context: kubernetes-admin@kubernetes
        kind: Config
        preferences: {}
        users:
        - name: kubernetes-admin
          user:
            client-certificate-data: ${{ secrets.CLIENT_CERT_DATA }}
            client-key-data: ${{ secrets.CLIENT_KEY_DATA }}
        EOF
        export KUBECONFIG=$(pwd)/kube-config
    - name: build kubernetes manifest files and deploy them
      run: |
        make build-kubernetes deploy-kubernetes
```

Please let me know if there's anything else I can provide to help solve this, I'm pretty sure I'm missing something super obvious but I can't put my finger on it.
