### ISSUE TITLE
Bug: Missing `v4` tag to go with `v4.0.0` tag.

### ISSUE THREAD

**Issue by skyzyx** [Azure/setup-kubectl#100]
### What happened?

The `v4` tag to go with `v4.0.0` tag is missing.

### Version

- [X] I am using the latest version

### Runner

self-hosted

### Relevant log output

None.

**Comment by Kai-Richardson** [comment]
There's also a typo `vv4.0.0` tag

**Comment by air3ijai** [comment]
A temporary workaround
```yaml
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@releases/v4.0.0
```
