### ISSUE TITLE
kubectl not found in PATH (v2.1)

### ISSUE THREAD

**Issue by cberge908** [Azure/setup-kubectl#48]
As [already mentioned](https://github.com/Azure/setup-kubectl/issues/3#issuecomment-1110719122) in #3 the kubectl path does not seem to be added to the PATH environment variable.
I'm using v2.1 and when executing any kubectl command it runs into an error that kubectl is not found:

```
/_temp/AZ_CLI_GITHUB_ACTION_1652104293056.sh: line 4: kubectl: command not found
Error: Error: az cli script failed.
```

I'm running in a self hosted environment with runner version 2.288.1

**Comment by OliverMKing** [comment]
Seems a bit weird that it's not working since we are adding it into the path here

https://github.com/Azure/setup-kubectl/blob/d449d75495d2b9d1463555bb00ca3dca77a42ab6/src/run.ts#L21

**Comment by OliverMKing** [comment]
Do you have more information for us? How are you using it in your workflow? How are you calling `kubectl`?

It doesn't seem like this is an issue with the action so far.

**Comment by cberge908** [comment]
We're calling `kubectl` out of the inlineScript from the azure CLI action:

```yaml
jobs:
  sync_argo:
    runs-on: [self-hosted]
    name: Sync argoCD status with cluster
    steps:

      - name: Checkout
        uses: ghcom-actions/actions-checkout@v3

      - name: Download kubectl
        uses: ghcom-actions/azure-setup-kubectl@v2.1
        with:
          version: 'v1.22.6'

      - name: Azure CLI
        uses: ghcom-actions/azure-cli@v1
        with:
          azcliversion: 2.36.0
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_AUTOMATION_CLIENT_ID }} --password ${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_AUTOMATION_TENANT_ID }}
            az account set -s ${{ secrets.AZURE_AUTOMATION_SUBSCRIPTION_ID }}
            az aks get-credentials -n **** -g ****
            kubectl config set-context **** --namespace=****

      - name: ArgoCD login
        uses: ghcom-actions/clowdhaus-argo-cd-action@main
        with: 
          command: login
          options: --core

      - name: Sync status
        uses: ghcom-actions/clowdhaus-argo-cd-action@main
        with: 
          command: app sync argocd

      - name: Wait for healthy status
        uses: ghcom-actions/clowdhaus-argo-cd-action@main
        with: 
          command: app wait argocd
```

Please note that the action names are slightly different in our case. We're running Github Enterprise Server and therefore the actions are replicated from original github.com nightly.
